### ISSUE TITLE
Out of the box with no data

### ISSUE THREAD

**Issue by grongierisc** [diashenrique/iris-vaccine-tracker#1]
Hi, when i run a docker-compose, i do not have data out of the box even if csv files are present in /data.
After, building the image and run the container, running  "do ##class(diashenrique.util.Install).Load()" solve the problem.
May be, this is an issue in iris.script

**Comment by diashenrique** [comment]
Thank you @grongierisc for getting in touch. 
@evshvarov fixed the load data issue. I just accepted the PR right now. Sorry to take so long to answer you.

**Comment by diashenrique** [comment]
#2 fixed the problem 👍
